spring:
  datasource:
    url: jdbc:h2:mem:school_prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: false
logging:
  level:
    com:
      example:
        bookstoremanager: INFO

jwt:
  secret: pwJKQorCQxnV1zS5Bn4GHX1RjR58KkRwwBu1mA5n8MBpmMS1oVboOymL7Xm03qwBTar6guldLtnmcWnI6hCzbg
  validity: 18000