INSERT INTO ADDRESS (ID, CEP, CITY, DISTRICT, NUMBER, STREET, UF) VALUES (1, '31333333', 'Bela Uberlândia', 'Uberonte', 10, 'Rua das Aroeiras', 'MG');
INSERT INTO ADDRESS (ID, CEP, CITY, DISTRICT, NUMBER, STREET, UF) VALUES (2, '31333333', 'Bela Uberlândia', 'Uberonte', 10, 'Rua das Aroeiras', 'MG');

INSERT INTO USER (PASSWORD, ROLE, USERNAME) VALUES ('$2a$10$rtgiRzcP2j0lxOB/EkTqaexCihAFc/r7OAelF1Zlhpkbxh1DBIGdu', 'ADMIN', 'joaodasneves');
INSERT INTO USER (PASSWORD, ROLE, USERNAME) VALUES ('$2a$10$qwTG4njwLQnIBhnlGm.qAe0Rn4vJsjY2RHjV5jF1vBBlaUx3/zxfC', 'RESPONSIBLE', 'irineia2');

INSERT INTO RESPONSIBLE (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, EMAIL, GENDER, IDENTITY_CARD, NAME, PHONE, PROFESSION, RELATIONSHIP_TYPE, ADDRESS_ID, USER_ID) VALUES (1, '1990-01-01', '34108198603', 'COMPLETE_HIGH_SCHOOL', 'resp@teste.com', 'FEMALE', '17333333', 'Irineia', '33333333', 'Auxiliar de escritório', 'MOTHER', 1, 2);

INSERT INTO STUDENT (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, GENDER, IDENTITY_CARD, NAME, PLACE_OF_BIRTH, SCHOOL, ADDRESS_ID) VALUES (1, '2012-01-01', '34108198603', 'INCOMPLETE_FUNDAMENTAL', 'MALE', '17333333', 'Pedro Henrique M', 'Bela Uberlândia', 'Escola Municipal de Bela Uberlândia', 2);
INSERT INTO STUDENT (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, GENDER, IDENTITY_CARD, NAME, PLACE_OF_BIRTH, SCHOOL, ADDRESS_ID) VALUES (2, '2012-01-01', '34108198603', 'INCOMPLETE_FUNDAMENTAL', 'MALE', '17111111', 'Pedro Henrique A', 'Bela Uberlândia', 'Escola Municipal de Bela Uberlândia', 2);
INSERT INTO STUDENT (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, GENDER, IDENTITY_CARD, NAME, PLACE_OF_BIRTH, SCHOOL, ADDRESS_ID) VALUES (3, '2012-01-01', '34108198603', 'INCOMPLETE_FUNDAMENTAL', 'FEMALE', '17222222', 'Jennifer', 'Bela Uberlândia', 'Escola Municipal de Bela Uberlândia', 2);

INSERT INTO RESPONSIBLE_STUDENT (RESPONSIBLE_ID, STUDENT_ID) VALUES (1, 1);
INSERT INTO RESPONSIBLE_STUDENT (RESPONSIBLE_ID, STUDENT_ID) VALUES (1, 2);
INSERT INTO RESPONSIBLE_STUDENT (RESPONSIBLE_ID, STUDENT_ID) VALUES (1, 3);

INSERT INTO OCCURRENCE (ID, COMMUNICATION_TYPE, DATE, DESCRIPTION, OCCURRENCE_TYPE, STUDENT_ID) VALUES (2, 'TO_PARENTS', '2020-01-01', 'Bateu no coleguinha', 'PHYSICAL_AGGRESSION', 1);
INSERT INTO OCCURRENCE (ID, COMMUNICATION_TYPE, DATE, DESCRIPTION, OCCURRENCE_TYPE, STUDENT_ID) VALUES (3, 'WRITTEN', '2021-01-01', 'Não obedeceu a professora', 'DISOBEDIENCE', 1);
INSERT INTO OCCURRENCE (ID, COMMUNICATION_TYPE, DATE, DESCRIPTION, OCCURRENCE_TYPE, STUDENT_ID) VALUES (1, 'WRITTEN', '2019-01-01', 'Saiu da sala sem avisar', 'DISOBEDIENCE', 1);

INSERT INTO COURSE (ID, NAME) VALUES (1, 'Vivência Pedagógica');
INSERT INTO COURSE (ID, NAME) VALUES (2, 'Esportes');
INSERT INTO COURSE (ID, NAME) VALUES (3, 'Artes Cênicas');
INSERT INTO COURSE (ID, NAME) VALUES (4, 'Música');

INSERT INTO EDUCATOR (ID, NAME, CPF, GENDER, COURSE_ID) VALUES (1, 'João', '66279751651', 'FEMALE', 1);
INSERT INTO EDUCATOR (ID, NAME, CPF, GENDER, COURSE_ID) VALUES (2, 'Miguel', '66279751651', 'FEMALE', 2);
INSERT INTO EDUCATOR (ID, NAME, CPF, GENDER, COURSE_ID) VALUES (3, 'Débora', '66279751651', 'FEMALE', 3);
INSERT INTO EDUCATOR (ID, NAME, CPF, GENDER, COURSE_ID) VALUES (4, 'Ana', '66279751651', 'FEMALE', 4);
