INSERT INTO ADDRESS (ID, CEP, CITY, DISTRICT, NUMBER, STREET, UF) VALUES (1, '31333333', 'Bela Uberlândia', 'Uberonte', 10, 'Rua das Aroeiras', 'MG');
INSERT INTO ADDRESS (ID, CEP, CITY, DISTRICT, NUMBER, STREET, UF) VALUES (2, '31333333', 'Bela Uberlândia', 'Uberonte', 10, 'Rua das Aroeiras', 'MG');
INSERT INTO USER (EMAIL, NAME, PASSWORD, ROLE, USERNAME) VALUES ('resp@teste.com', 'Nome de test', '$2a$10$0T5vPQ1Plx2LpH4L8mRIF.zvceMI6S6n91h1Zcxnue3xCrIG0B9Pa', 'RESPONSIBLE', 'test');
INSERT INTO RESPONSIBLE (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, EMAIL, GENDER, IDENTITY_CARD, NAME, PHONE, PROFESSION, RELATIONSHIP_TYPE, ADDRESS_ID, USER_ID) VALUES (1, '1990-01-01', '34108198603', 'COMPLETE_HIGH_SCHOOL', 'resp@teste.com', 'FEMALE', '17333333', 'Nome de test', '33333333', 'Auxiliar de escritório', 'MOTHER', 1, 1);
INSERT INTO STUDENT (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, GENDER, IDENTITY_CARD, NAME, PLACE_OF_BIRTH, SCHOOL, ADDRESS_ID) VALUES (1, '2012-01-01', '34108198603', 'INCOMPLETE_FUNDAMENTAL', 'MALE', '17333333', 'Pedro Henrique', 'Bela Uberlândia', 'Escola Municipal de Bela Uberlândia', 2);
INSERT INTO STUDENT (ID, BIRTHDATE, CPF, EDUCATIONAL_LEVEL, GENDER, IDENTITY_CARD, NAME, PLACE_OF_BIRTH, SCHOOL, ADDRESS_ID) VALUES (2, '2012-01-01', '34108198603', 'INCOMPLETE_FUNDAMENTAL', 'MALE', '17333333', 'Pedro Henrique', 'Bela Uberlândia', 'Escola Municipal de Bela Uberlândia', 2);
INSERT INTO RESPONSIBLE_STUDENT (RESPONSIBLE_ID, STUDENT_ID) VALUES (1, 1);
INSERT INTO RESPONSIBLE_STUDENT (RESPONSIBLE_ID, STUDENT_ID) VALUES (1, 2);


INSERT INTO OCCURRENCE (ID, COMMUNICATION_TYPE, DATE, DESCRIPTION, OCCURRENCE_TYPE, STUDENT_ID) VALUES (1, 'ESCRITO', '2021-01-01', 'Bateu no coleguinha', 'AGRESSAO_FISICA', 1)

