package uol.compass.school.enums;

public enum EducationalLevel {

    INCOMPLETE_FUNDAMENTAL,
    COMPLETE_FUNDAMENTAL,
    INCOMPLETE_HIGH_SCHOOL,
    COMPLETE_HIGH_SCHOOL,
    INCOMPLETE_UNIVERSITY_EDUCATION,
    COMPLETE_UNIVERSITY_EDUCATION
}
