package uol.compass.school.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum EducationalLevel {

    INCOMPLETE_FUNDAMENTAL("INCOMPLETE FUNDAMENTAL"),
    COMPLETE_FUNDAMENTAL("COMPLETE FUNDAMENTAL"),
    INCOMPLETE_HIGH_SCHOOL("INCOMPLETE HIGH SCHOOL"),
    COMPLETE_HIGH_SCHOOL("COMPLETE HIGH SCHOOL"),
    INCOMPLETE_UNIVERSITY_EDUCATION("INCOMPLETE UNIVERSITY EDUCATION"),
    COMPLETE_UNIVERSITY_EDUCATION("COMPLETE UNIVERSITY EDUCATION");

    private String description;
}